name: CI Workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - run: cd backend && npm install
      - run: cd backend && npm run build

   lint:
    name: 🧼 Ensure Code Style
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 16
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Install deps
        run: cd backend && npm i

      - name: 😂 Lint code
        run: cd backend && npm run lint