name: CI Workflow
on: 
  push:
    branch: olt
    
name: Continuous Integration
on:
  [push]


jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      run: cd backend && npm install
      run: cd backend && npm run build
 
      